server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/spin {
        proxy_pass https://casino-game.fly.dev/api/spin;
        proxy_set_header Host casino-game.fly.dev;
        proxy_ssl_server_name on;
    }

    location /api/ {
        proxy_pass https://casino-wallet.fly.dev/api/;
        proxy_set_header Host casino-wallet.fly.dev;
        proxy_ssl_server_name on;
    }
}
