server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # API Documentation (Swagger)
    location /docs {
        alias /usr/share/nginx/html;
        try_files /docs.html =404;
    }

    # Proxy to Game Service (Roulette & Blackjack)
    location /api/spin {
        proxy_pass http://game-service:8082/api/spin;
    }

    location /api/blackjack/ {
        proxy_pass http://game-service:8082/api/blackjack/;
    }

    # Proxy to Wallet Service
    location /api/ {
        proxy_pass http://wallet-service:8081/api/;
    }
}
